#ifndef _VERSION_INFO_H_
#define _VERSION_INFO_H_

#define POLARDBX_CPPCONN_MAJOR_VERSION @POLARDBX_VERSION_MAJOR@
#define POLARDBX_CPPCONN_MINOR_VERSION @POLARDBX_VERSION_MINOR@
#define POLARDBX_CPPCONN_PATCH_VERSION @POLARDBX_VERSION_PATCH@

#endif // _VERSION_INFO_H_